workflows:
  ios_ipa_nosign:
    name: iOS IPA (no codesign)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter doctor
        script: |
          flutter --version
          flutter doctor -v

      - name: Get packages
        script: flutter pub get

      - name: Ensure iOS platform
        script: |
          if [ ! -d "ios" ]; then
            flutter create . --platforms=ios --project-name alexx626
          fi

      - name: Build Xcode archive (no codesign)
        script: |
          flutter build ios --release --no-codesign
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath build/ios/archive/Runner.xcarchive \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""

      - name: Export IPA
        script: |
          mkdir -p build/ios/ipa
          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>ad-hoc</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>compileBitcode</key>
            <false/>
            <key>stripSwiftSymbols</key>
            <true/>
          </dict>
          </plist>
          EOF
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ios/ipa \
            CODE_SIGNING_ALLOWED=NO

    artifacts:
      - build/ios/ipa/*.ipa
