workflows:
  ios_ipa_nosign:
    name: iOS IPA (manual package, no codesign)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter doctor
        script: |
          flutter --version
          flutter doctor -v

      - name: Get packages
        script: flutter pub get

      - name: Ensure iOS platform
        script: |
          if [ ! -d "ios" ]; then
            echo "⚡ Generating iOS project..."
            flutter create . --platforms=ios --project-name alexx626
          else
            echo "✅ iOS folder already exists."
          fi

      - name: Build iOS app (no codesign)
        script: |
          flutter clean
          flutter pub get
          # construim .app fără semnare
          flutter build ios --release --no-codesign
          ls -la build/ios/iphoneos || true

      - name: Package unsigned IPA (manual)
        script: |
          set -e
          APP_PATH="build/ios/iphoneos/Runner.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "❌ Runner.app not found at $APP_PATH"
            exit 1
          fi

          # Curățăm semnăturile vechi (dacă există)
          rm -rf "$APP_PATH/_CodeSignature" || true
          rm -f "$APP_PATH/embedded.mobileprovision" || true

          # Împachetăm ca .ipa nesemnat
          mkdir -p build/ios/ipa
          mkdir -p payload/Payload
          cp -R "$APP_PATH" "payload/Payload/Runner.app"

          (cd payload && zip -qry ../build/ios/ipa/Alexx626-unsigned.ipa Payload)

          echo "✅ Unsigned IPA created at build/ios/ipa/Alexx626-unsigned.ipa"

    artifacts:
      - build/ios/ipa/*.ipa
