workflows:
  ios_ipa_nosign:
    name: iOS IPA (no codesign)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Build IPA (no codesign)
        script: flutter build ipa --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
